http.host: 0.0.0.0
network.host: 0.0.0.0

bootstrap.memory_lock: true

# Cluster settings
cluster.name: es-cluster

# Uncomment the following lines for a production cluster deployment
discovery.zen.ping.unicast.hosts: ['es_container01', 'es_container02', 'es_container03']
discovery.zen.minimum_master_nodes: 2

### x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false

### x-pack functions
# xpack.security.enabled: false
# xpack.monitoring.enabled: true
# xpack.graph.enabled: true
# xpack.watcher.enabled: false