FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.4

# kuromojiをインストール
# RUN elasticsearch-plugin install analysis-kuromoji
# RUN elasticsearch-plugin list

# RUN elasticsearch-plugin install elasticsearch-analysis-kuromoji-neologd
# RUN elasticsearch-plugin install elasticsearch-analysis-kuromoji-ipadic-neologd
# RUN elasticsearch-plugin install elasticsearch-analysis-kuromoji-neologd
# RUN elasticsearch-plugin install mobz/elasticsearch-head
